### ISSUE TITLE
observer_slot について

### ISSUE THREAD

**Issue by execut1ve** [Thiry1/csgo-custom-hud#12]
https://github.com/Thiry1/csgo-custom-hud/blob/31176fbc8792f209a515b1d10ce4388c401df9ee/src/dataTypes/index.ts#L240

おそらく、`observer_slot`  は観戦しているプレイヤーの識別番号です。数字キー0～9を押すとそのプレイヤーになる、ってやつ。あとレーダーにも表示されてます。
どうもこのデータが取れていない(おそらく現状意図的に取っていない？)ようで、どうにか弄ってみたのですが自分の力ではエラー吐きまくってアレだったので、実装お願いしたいです。

この番号が取れたら `SpectatingPlayer.tsx` で例えば「n番のプレイヤーを観戦してるときはn番のTwitterIDを表示」みたいなことができるようになるはずです。

よろしくお願いします。

**Comment by Thiry1** [comment]
@execut1ve 
>おそらく、observer_slot は観戦しているプレイヤーの識別番号です。数字キー0～9を押すとそのプレイヤーになる、ってやつ

おお、なるほど。

>どうもこのデータが取れていない(おそらく現状意図的に取っていない？)ようで

ご指摘の通りユースケースがなかったので現状取っていないです。取得自体はすぐ可能なので必要があれば対応します。

>この番号が取れたら SpectatingPlayer.tsx で例えば「n番のプレイヤーを観戦してるときはn番のTwitterIDを表示」みたいなことができるようになるはずです。

`observer_slot` の値はおそらくプレイヤーの接続順等で変動するのではないかという気がしています。
とある人のTwitterIDを表示したいというケースでは、SteamIDとTwitterIDを紐づけておくのが一番楽かつ確実かなと思っています。

**Comment by Thiry1** [comment]
タスクに積んだので、よきタイミングで実装します

**Comment by Thiry1** [comment]
0a23406622c5a62dd77e252d4276486fa51ef3ff で Twitter IDの表示に対応させた
