### ISSUE TITLE
ハーフ切り替え後に観戦キーの組み合わせがおかしくなる

### ISSUE THREAD

**Issue by ruk1ium** [Thiry1/csgo-custom-hud#14]
標準HUDではハーフタイムで陣営が変わると画面右側と左側のプレイヤー表示も入れ替わり、キーボードの1~9,0の数字も対応するようになっています。
今こちらのHUDだと、ハーフタイムの陣営交代後[1]キーを押しても[6]のプレイヤーに視点が切り替わってしまうので、15ラウンド目が終了した際に自動でスワップするかAlt+Leftでプレイヤー情報も入れ替えできるようになると便利になると思います。

**Comment by ruk1ium** [comment]
Alt+Left を押してもチーム名しか切り替わらないので、ハーフタイム後スコアとチーム名表示の切り替えがおかしくなっています。
Alt+Leftでチーム名、ロゴ、スコア、HPバーが切り替わるようにすれば治ると思います

**Comment by Thiry1** [comment]
チーム名が入れ替わり続けるバグは #23 で指摘されて修正を行いました。
ほかは問題なさそうとのことなのでcloseしてしまいます
