### ISSUE TITLE
Winner Team Message and Defusing animation

### ISSUE THREAD

**Issue by glockmaster** [Thiry1/csgo-custom-hud#15]
Hi,

There is missing two functions of what team winns and defusing animation.

Regards

**Comment by Thiry1** [comment]
@glockmaster hi. 
These are under developing.
So please wait for completion

**Comment by Thiry1** [comment]
I have just implemented defusing animation.

**Comment by glockmaster** [comment]
Thanks, 

I will try :D

**Comment by Thiry1** [comment]
I have just implemented Winner Team Message.
Now, I close this issue :D
