### ISSUE TITLE
*Bug* "Winner" message isnt fully centered.

### ISSUE THREAD

**Issue by LukasW1337** [Thiry1/csgo-custom-hud#17]
The winner message isn't fully centered. It seems to center aroundjust the team name maybe?
![unnamed](https://user-images.githubusercontent.com/33436545/38964288-4c76e18a-4376-11e8-8fa7-437b5ac61afb.png)

![unavngivet2](https://user-images.githubusercontent.com/33436545/38964311-6877140e-4376-11e8-82ff-fcc4a0bd7234.png)

**Comment by Thiry1** [comment]
Oops.I'll fix it.
Thanks for your report.

**Comment by Thiry1** [comment]
fixed.
https://github.com/Thiry1/csgo-custom-hud/commit/21c66e4bc5ec79c706ee67304d71d7d7482a2772
