### ISSUE TITLE
タスクバーがある状態でnpm startするとタスクバーの高さを含んだ状態で描画される

### ISSUE THREAD

**Issue by execut1ve** [Thiry1/csgo-custom-hud#19]
Windows10,1920x1080,タスクバー40pxの場合、
npm startした後のウィンドウが1920x1040になる。

回避方法：タスクバーを隠した状態でnpm startすると1920x1080で起動する

ps. タイトルの日本語がおかしかったけど伝わってください😂

**Comment by Thiry1** [comment]
これは残念ながらnw.jsの仕様の為修正不可です 😭
