### ISSUE TITLE
decoy grenades aren't displayed

### ISSUE THREAD

**Issue by nppb** [Thiry1/csgo-custom-hud#22]
First of all, thank you very much for the effort you put in so far Thiry1. I really appreciate this project.

I discovered recently that decoy grenades wouldnt show up in the HUD for one of the 2 teams. I'm not entirely sure, but I think this applies only to the team on a certain side of the HUD (the left side) as seen in the screenshot. So if the teams switch after halftime the bug continues for the other team.

![decoybug_marked](https://user-images.githubusercontent.com/37812438/39523277-48c39836-4e15-11e8-84bd-1980c4355c1f.png)

Again, thank you very much for your work so far.

**Comment by Thiry1** [comment]
@nppb Thank you for report!
I just fixed this issue via b789f9469ca91917d7dc1fda7980e5e6fb92010c
