### ISSUE TITLE
Bug when halftime starts/ends

### ISSUE THREAD

**Issue by LukasW1337** [Thiry1/csgo-custom-hud#23]
[Look at this video](https://youtu.be/PW_ybBnFlxU?t=2m43s) - wait the 10 sec countdown out and see the team names/logos

They keep shifting right and left all the time - without any input from operator.

**Comment by nppb** [comment]
I can confirm this bug, as its happening to me every halftime. 
However I'm not entirely sure whether it's the overlay itself or the output of the game.

**Comment by Thiry1** [comment]
What a terrible bug!
I'll fix asap

**Comment by Thiry1** [comment]
fixed via bd90d328b254a52989a5ec99b36eff6fb4397ea0
