### ISSUE TITLE
ハーフタイム時にHPバーの「デザイン」を左右で切り替えるようにする

### ISSUE THREAD

**Issue by execut1ve** [Thiry1/csgo-custom-hud#41]
現在、ハーフタイム時に左右HPバーのの **情報** が切り替わるようになっていますが、これをチームカラー等の **デザイン** が切り替わるようにしてほしいです。

CS:GOの観戦HUDはデフォルトで左右のデザインが切り替わるようになっており、プレイヤーはobserver_slotの値に応じて左上から1～5、右上から6～0のプレイヤーが割り当てられるようになっています。1～5と6～0は `cl_spec_swapplayersides` でそれぞれ切り替えが可能です。

参考
https://youtu.be/mq_9Izw730g?t=44m39s
https://youtu.be/NC_qkchKyao?t=34m28s

**Comment by Thiry1** [comment]
observer_sloの値が表示されていたほうが開発時に都合が良さそうなので #40 を優先しました。次はこのissueの対応やります

**Comment by Thiry1** [comment]
teamがTかCTかでcssを設定していたところを整理する必要がある。
data-teamでは色情報などを設定して、data-slot-side="left | right" では位置情報を設定するように変更すれば良さそう。

**Comment by Thiry1** [comment]
対応したのでclose
