### ISSUE TITLE
MP5-SD icon missing

### ISSUE THREAD

**Issue by nppb** [Thiry1/csgo-custom-hud#45]
![mp5](https://user-images.githubusercontent.com/37812438/44468005-8e3a0280-a624-11e8-9231-e202f198fa76.png)
The icon of the newly added MP5-SD is missing on the playerlist. 

Thank you for the constant work you put in!

Kind regards, nppb.

**Comment by Thiry1** [comment]
Wow, new weapon!
I'll update weapon icon for MP5.
Thank you for report!

**Comment by Thiry1** [comment]
added.
https://github.com/Thiry1/csgo-custom-hud/commit/c9798c0af6df119d947e21b76c36e7be9ebf19af
