### ISSUE TITLE
観戦中にカメラをフリールックにすると観戦者情報が正しく更新されない

### ISSUE THREAD

**Issue by Thiry1** [Thiry1/csgo-custom-hud#6]

**Comment by Thiry1** [comment]
カメラをフリールックにすると観戦中のプレイヤー情報に観戦者自身(= HUDの利用者)のデータが入るという天才仕様だった。

**Comment by ruk1ium** [comment]
GSI側の観戦者情報ですが、GOTVか、そうじゃないかで表示される情報が違うかもしれません。
GOTVの場合は、多分GOTV自体がプレイヤーとしてGSI側に認識されてると思います。
動画の39秒から画面下に[GOTV]と表示されているので...(間違っていたらすいません)
https://www.youtube.com/watch?v=veWbLtXPvVg

**Comment by Thiry1** [comment]
なるほど...。TかCTにいる人以外は表示しない感じの対応をしたのでGOTVも現れることはないはずですが、謎仕様ですね...
