### ISSUE TITLE
Upper HUD (Team Scores & Round Time)

### ISSUE THREAD

**Issue by morpig** [Thiry1/csgo-custom-hud#7]
Hi there,

I tried running your app and it's amazing especially it runs with React. During my test, I can't see the upper HUD, is it not added or is it a bug?

Example:
![image](https://user-images.githubusercontent.com/4915643/37093648-a8629d0e-2242-11e8-90a8-77624904a516.png)

Thanks!

**Comment by Thiry1** [comment]
@morpig 
It's under development.
It is scheduled to be completed in about a week.
Thank you for your report!

**Comment by Thiry1** [comment]
added.

**Comment by glockmaster** [comment]
I cant change the name of the teams and add their logo even using the teams.ts

**Comment by Thiry1** [comment]
@glockmaster You need to rebuild the program following steps.
1. edit the team.ts
2. npm run build
3. npm start

**Comment by glockmaster** [comment]
Is possible to add the flags under the logos?
